ConfigName: Logging configuration name
Directory: "/build/test_files"
LogPattern: "\\[(?P<timestamp>%s)\\]\\[(?P<level>%s)\\]\\[(?P<code>%s)\\]\\s(?P<message>%s)"
Definitions:
  - Name: DatePattern
    Pattern: "\\d{4}-\\d{2}-\\d{2}\\s\\d{2}:\\d{2}:\\d{2}\\.\\d{6}\\s[A-Z]{3}"
  - Name: LogLevelPattern
    Pattern: "ERROR|WARN|WARNING|INFO|DEBUG"
  - Name: LogCodePattern
    Pattern: "[0-9]+?"
  - Name: LogMsgPattern
    Pattern: ".*"
S3Connectors:
  - Name: testS3Connector
    Type: s3
    Region: us-east-1
    Endpoint: http://localstack:4572
    KeyPrefix: test-application
    Bucket: local-test-bucket
    Levels:
      - DEBUG
      - INFO
      - WARNING
      - ERROR
RollbarConnectors:
  - Name: testRollbarConnector
    Type: rollbar
    Url: www.rollbar.com/something
    Levels:
      - WARNING
      - ERROR
KafkaConnectors:
  - Name: testKafkaConnector
    Type: kafka
    Host: localhost
    Port: 9092
    Topic: test-kafka-topic
    Levels:
      - DEBUG
      - INFO
      - WARNING
      - ERROR
      